(() => {
 'use strict';
 const initial={data:window.JCID_BOARD,readings:window.JCID_READINGS,nc:window.JCID_NC_DISPLAY,imageSource:'fontes-previas/iphone11-placa-principal.jpg'},primary='iphone-11-motherboard';
 const states=new Map(),cache=new Map();let current=primary,currentUrl=null,currentData=initial,serial=0,controller=null;
 window.JCID_ACTIVE_BOARD={id:primary,modelId:'iphone-11',schematic:true};
 function valid(data){const box=b=>Array.isArray(b)&&b.length===4&&b.every(Number.isFinite)&&b[2]>=b[0]&&b[3]>=b[1];if(data?.version!==2||!box(data.bounds)||data.bounds[2]===data.bounds[0]||data.bounds[3]===data.bounds[1]||!['components','pins','boards','nets','layers'].every(k=>Array.isArray(data[k]))||!data.pins.length||!data.components.length)throw Error('Geometria indisponível para esta placa.');if(!data.pins.every((p,i)=>p.id===i&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&box(p.bbox))||!data.components.every(c=>box(c.bbox)))throw Error('Não foi possível validar as posições desta placa.');}
 function remember(){states.set(current,window.JCIDBoardView.snapshot());}
 function trim(){while(cache.size>2)cache.delete(cache.keys().next().value);}
 async function get(item,signal){if(item.id===primary&&!item.board_data)return initial;if(cache.has(item.id)&&cache.get(item.id).sourceUrl===item.board_data){const found=cache.get(item.id);cache.delete(item.id);cache.set(item.id,found);return found;}if(!item.board_data)throw Error('Mapa ainda não preparado.');const response=await fetch(item.board_data,{signal});if(!response.ok)throw Error('Não foi possível abrir os dados desta placa.');const data=await response.json();valid(data);const payload={data,readings:data.readings||{label:'Diodo',pins:{}},nc:data.ncDisplay||{},sourceUrl:item.board_data,imageSource:data.imageSource?(window.NexusLibrary?.localResource(item,data.imageSource)||(!item.nexus_package?data.imageSource:null)):null};cache.set(item.id,payload);trim();return payload;}
 function globals(payload){window.JCID_BOARD=payload.data;window.JCID_READINGS=payload.readings;window.JCID_NC_DISPLAY=payload.nc;}
 function busy(value,label){document.body.classList.toggle('board-loading',value);const loading=document.getElementById('loading');loading.hidden=!value;if(value)loading.textContent='Abrindo '+label+'…';window.dispatchEvent(new CustomEvent('jcid:boardloadstate'));}
 async function load(item,model){const token=++serial;controller?.abort();controller=new AbortController();if(item.id===current&&(item.board_data||null)===currentUrl){busy(false);return true;}busy(true,model.label+' · '+item.label);const old=currentData,oldId=current,oldMeta=window.JCID_ACTIVE_BOARD;try{const next=await get(item,controller.signal);if(token!==serial)return false;await new Promise(resolve=>setTimeout(resolve,0));if(token!==serial)return false;remember();window.JCIDBoardView.destroy();globals(next);window.JCID_ACTIVE_BOARD={id:item.id,modelId:model.id,schematic:(window.JCID_SCHEMATICS?.documents||[]).some(d=>d.modelIds.includes(model.id))};try{window.createJCIDBoardView(next.data,next.readings,next.nc,{imageSource:next.imageSource,snapshot:states.get(item.id),skipQuery:true});}catch(error){window.__activeBoardView?.destroy();globals(old);window.JCID_ACTIVE_BOARD=oldMeta;window.createJCIDBoardView(old.data,old.readings,old.nc,{imageSource:old.imageSource,snapshot:states.get(oldId),skipQuery:true});window.JCID_ACTIVE_BOARD=oldMeta;throw error;}current=item.id;currentUrl=item.board_data||null;currentData=next;window.JCID_ACTIVE_BOARD={id:item.id,modelId:model.id,schematic:(window.JCID_SCHEMATICS?.documents||[]).some(d=>d.modelIds.includes(model.id))};window.dispatchEvent(new CustomEvent('jcid:boardchange',{detail:window.JCID_ACTIVE_BOARD}));return true;}catch(error){if(token!==serial||error.name==='AbortError')return false;throw error;}finally{if(token===serial)busy(false);}}
 function cancel(){serial++;controller?.abort();busy(false);}
 window.JCIDBoards=Object.freeze({load,cancel,current:()=>current,forget:id=>{if(id!==current){states.delete(id);cache.delete(id);}}});
})();
